module tb_case_009(
  input                  axim_clk_en,
  input                  pad_biu_arready,
  input                  pad_biu_awready,
  input      [7 : 0]     pad_biu_bid,
  input      [1 : 0]     pad_biu_bresp,
  input                  pad_biu_bvalid,
  input      [127 : 0]   pad_biu_rdata,
  input      [7 : 0]     pad_biu_rid,
  input                  pad_biu_rlast,
  input      [3 : 0]     pad_biu_rresp,
  input                  pad_biu_rvalid,
  input                  pad_biu_wready,
  input                  pad_cpu_rst_b,
  input                  pad_had_jtg_tclk,
  input                  pad_had_jtg_tdi,
  input                  pad_had_jtg_trst_b,
  input                  pad_yy_dft_clk_rst_b,
  input                  pll_cpu_clk,
  output     [39 : 0]    biu_pad_araddr,
  output     [1 : 0]     biu_pad_arburst,
  output     [3 : 0]     biu_pad_arcache,
  output     [7 : 0]     biu_pad_arid,
  output     [7 : 0]     biu_pad_arlen,
  output                 biu_pad_arlock,
  output     [2 : 0]     biu_pad_arprot,
  output     [2 : 0]     biu_pad_arsize,
  output                 biu_pad_arvalid,
  output     [39 : 0]    biu_pad_awaddr,
  output     [1 : 0]     biu_pad_awburst,
  output     [3 : 0]     biu_pad_awcache,
  output     [7 : 0]     biu_pad_awid,
  output     [7 : 0]     biu_pad_awlen,
  output                 biu_pad_awlock,
  output     [2 : 0]     biu_pad_awprot,
  output     [2 : 0]     biu_pad_awsize,
  output                 biu_pad_awvalid,
  output                 biu_pad_bready,
  output                 biu_pad_rready,
  output     [127 : 0]   biu_pad_wdata,
  output                 biu_pad_wlast,
  output     [15 : 0]    biu_pad_wstrb,
  output                 biu_pad_wvalid,
  output                 had_pad_jtg_tdo,
  output                 had_pad_jtg_tdo_en,
`ifdef PMU_LP_MODE_TEST
  input                  pmu_cpu_pwr_on,
  input                  pmu_cpu_iso_in,
  input                  pmu_cpu_iso_out,
  input                  pmu_cpu_save,
  input                  pmu_cpu_restore,
`endif
  input      [39 : 0]    xx_intc_vld,
  input                  per_clk,
  input                  i_pad_jtg_tms,
  output     [7 : 0]     biu_pad_wid,
  output     [1 : 0]     biu_pad_lpmd_b
);

  cpu_sub_system_axi dut (
    .axim_clk_en(axim_clk_en),
    .pad_biu_arready(pad_biu_arready),
    .pad_biu_awready(pad_biu_awready),
    .pad_biu_bid(pad_biu_bid),
    .pad_biu_bresp(pad_biu_bresp),
    .pad_biu_bvalid(pad_biu_bvalid),
    .pad_biu_rdata(pad_biu_rdata),
    .pad_biu_rid(pad_biu_rid),
    .pad_biu_rlast(pad_biu_rlast),
    .pad_biu_rresp(pad_biu_rresp),
    .pad_biu_rvalid(pad_biu_rvalid),
    .pad_biu_wready(pad_biu_wready),
    .pad_cpu_rst_b(pad_cpu_rst_b),
    .pad_had_jtg_tclk(pad_had_jtg_tclk),
    .pad_had_jtg_tdi(pad_had_jtg_tdi),
    .pad_had_jtg_trst_b(pad_had_jtg_trst_b),
    .pad_yy_dft_clk_rst_b(pad_yy_dft_clk_rst_b),
    .pll_cpu_clk(pll_cpu_clk),
    .biu_pad_araddr(biu_pad_araddr),
    .biu_pad_arburst(biu_pad_arburst),
    .biu_pad_arcache(biu_pad_arcache),
    .biu_pad_arid(biu_pad_arid),
    .biu_pad_arlen(biu_pad_arlen),
    .biu_pad_arlock(biu_pad_arlock),
    .biu_pad_arprot(biu_pad_arprot),
    .biu_pad_arsize(biu_pad_arsize),
    .biu_pad_arvalid(biu_pad_arvalid),
    .biu_pad_awaddr(biu_pad_awaddr),
    .biu_pad_awburst(biu_pad_awburst),
    .biu_pad_awcache(biu_pad_awcache),
    .biu_pad_awid(biu_pad_awid),
    .biu_pad_awlen(biu_pad_awlen),
    .biu_pad_awlock(biu_pad_awlock),
    .biu_pad_awprot(biu_pad_awprot),
    .biu_pad_awsize(biu_pad_awsize),
    .biu_pad_awvalid(biu_pad_awvalid),
    .biu_pad_bready(biu_pad_bready),
    .biu_pad_rready(biu_pad_rready),
    .biu_pad_wdata(biu_pad_wdata),
    .biu_pad_wlast(biu_pad_wlast),
    .biu_pad_wstrb(biu_pad_wstrb),
    .biu_pad_wvalid(biu_pad_wvalid),
    .had_pad_jtg_tdo(had_pad_jtg_tdo),
    .had_pad_jtg_tdo_en(had_pad_jtg_tdo_en),
`ifdef PMU_LP_MODE_TEST
    .pmu_cpu_pwr_on(pmu_cpu_pwr_on),
    .pmu_cpu_iso_in(pmu_cpu_iso_in),
    .pmu_cpu_iso_out(pmu_cpu_iso_out),
    .pmu_cpu_save(pmu_cpu_save),
    .pmu_cpu_restore(pmu_cpu_restore),
`endif
    .xx_intc_vld(xx_intc_vld),
    .per_clk(per_clk),
    .i_pad_jtg_tms(i_pad_jtg_tms),
    .biu_pad_wid(biu_pad_wid),
    .biu_pad_lpmd_b(biu_pad_lpmd_b)
  );
endmodule
