module tb_case_005(
  input         cp0_mmu_icg_en,
  input         cpurst_b,
  input         entry0_vld,
  input         entry10_vld,
  input         entry11_vld,
  input         entry12_vld,
  input         entry13_vld,
  input         entry14_vld,
  input         entry15_vld,
  input         entry1_vld,
  input         entry2_vld,
  input         entry3_vld,
  input         entry4_vld,
  input         entry5_vld,
  input         entry6_vld,
  input         entry7_vld,
  input         entry8_vld,
  input         entry9_vld,
  input         forever_cpuclk,
  input         pad_yy_icg_scan_en,
  input  [15:0] utlb_plru_read_hit0,
  input  [15:0] utlb_plru_read_hit1,
  input         utlb_plru_read_hit_vld0,
  input         utlb_plru_read_hit_vld1,
  input         utlb_plru_refill_on,
  input         utlb_plru_refill_vld,
  output [15:0] plru_dutlb_ref_num
);

  ct_mmu_dplru dut (
    .cp0_mmu_icg_en(cp0_mmu_icg_en),
    .cpurst_b(cpurst_b),
    .entry0_vld(entry0_vld),
    .entry10_vld(entry10_vld),
    .entry11_vld(entry11_vld),
    .entry12_vld(entry12_vld),
    .entry13_vld(entry13_vld),
    .entry14_vld(entry14_vld),
    .entry15_vld(entry15_vld),
    .entry1_vld(entry1_vld),
    .entry2_vld(entry2_vld),
    .entry3_vld(entry3_vld),
    .entry4_vld(entry4_vld),
    .entry5_vld(entry5_vld),
    .entry6_vld(entry6_vld),
    .entry7_vld(entry7_vld),
    .entry8_vld(entry8_vld),
    .entry9_vld(entry9_vld),
    .forever_cpuclk(forever_cpuclk),
    .pad_yy_icg_scan_en(pad_yy_icg_scan_en),
    .plru_dutlb_ref_num(plru_dutlb_ref_num),
    .utlb_plru_read_hit0(utlb_plru_read_hit0),
    .utlb_plru_read_hit1(utlb_plru_read_hit1),
    .utlb_plru_read_hit_vld0(utlb_plru_read_hit_vld0),
    .utlb_plru_read_hit_vld1(utlb_plru_read_hit_vld1),
    .utlb_plru_refill_on(utlb_plru_refill_on),
    .utlb_plru_refill_vld(utlb_plru_refill_vld)
  );
endmodule
