module tb_case_001(
  input            cp0_ifu_icache_en,
  input            cp0_ifu_icg_en,
  input            cp0_yy_clk_en,
  input            cpurst_b,
  input            forever_cpuclk,
  input            hpcp_ifu_cnt_en,
  input   [38 :0]  ifctrl_icache_if_index,
  input            ifctrl_icache_if_inv_fifo,
  input            ifctrl_icache_if_inv_on,
  input            ifctrl_icache_if_read_req_data0,
  input            ifctrl_icache_if_read_req_data1,
  input   [38 :0]  ifctrl_icache_if_read_req_index,
  input            ifctrl_icache_if_read_req_tag,
  input            ifctrl_icache_if_reset_req,
  input            ifctrl_icache_if_tag_req,
  input   [2  :0]  ifctrl_icache_if_tag_wen,
  input            ifu_hpcp_icache_miss_pre,
  input   [33 :0]  ipb_icache_if_index,
  input            ipb_icache_if_req,
  input            ipb_icache_if_req_for_gateclk,
  input            l1_refill_icache_if_fifo,
  input            l1_refill_icache_if_first,
  input   [38 :0]  l1_refill_icache_if_index,
  input   [127:0]  l1_refill_icache_if_inst_data,
  input            l1_refill_icache_if_last,
  input   [31 :0]  l1_refill_icache_if_pre_code,
  input   [27 :0]  l1_refill_icache_if_ptag,
  input            l1_refill_icache_if_wr,
  input            pad_yy_icg_scan_en,
  input            pcgen_icache_if_chgflw,
  input            pcgen_icache_if_chgflw_bank0,
  input            pcgen_icache_if_chgflw_bank1,
  input            pcgen_icache_if_chgflw_bank2,
  input            pcgen_icache_if_chgflw_bank3,
  input            pcgen_icache_if_chgflw_short,
  input            pcgen_icache_if_gateclk_en,
  input   [15 :0]  pcgen_icache_if_index,
  input            pcgen_icache_if_seq_data_req,
  input            pcgen_icache_if_seq_data_req_short,
  input            pcgen_icache_if_seq_tag_req,
  input   [1  :0]  pcgen_icache_if_way_pred,
  output  [127:0]  icache_if_ifctrl_inst_data0,
  output  [127:0]  icache_if_ifctrl_inst_data1,
  output  [28 :0]  icache_if_ifctrl_tag_data0,
  output  [28 :0]  icache_if_ifctrl_tag_data1,
  output           icache_if_ifdp_fifo,
  output  [127:0]  icache_if_ifdp_inst_data0,
  output  [127:0]  icache_if_ifdp_inst_data1,
  output  [31 :0]  icache_if_ifdp_precode0,
  output  [31 :0]  icache_if_ifdp_precode1,
  output  [28 :0]  icache_if_ifdp_tag_data0,
  output  [28 :0]  icache_if_ifdp_tag_data1,
  output  [28 :0]  icache_if_ipb_tag_data0,
  output  [28 :0]  icache_if_ipb_tag_data1,
  output           ifu_hpcp_icache_access,
  output           ifu_hpcp_icache_miss
);

  ct_ifu_icache_if dut (
    .cp0_ifu_icache_en(cp0_ifu_icache_en),
    .cp0_ifu_icg_en(cp0_ifu_icg_en),
    .cp0_yy_clk_en(cp0_yy_clk_en),
    .cpurst_b(cpurst_b),
    .forever_cpuclk(forever_cpuclk),
    .hpcp_ifu_cnt_en(hpcp_ifu_cnt_en),
    .ifctrl_icache_if_index(ifctrl_icache_if_index),
    .ifctrl_icache_if_inv_fifo(ifctrl_icache_if_inv_fifo),
    .ifctrl_icache_if_inv_on(ifctrl_icache_if_inv_on),
    .ifctrl_icache_if_read_req_data0(ifctrl_icache_if_read_req_data0),
    .ifctrl_icache_if_read_req_data1(ifctrl_icache_if_read_req_data1),
    .ifctrl_icache_if_read_req_index(ifctrl_icache_if_read_req_index),
    .ifctrl_icache_if_read_req_tag(ifctrl_icache_if_read_req_tag),
    .ifctrl_icache_if_reset_req(ifctrl_icache_if_reset_req),
    .ifctrl_icache_if_tag_req(ifctrl_icache_if_tag_req),
    .ifctrl_icache_if_tag_wen(ifctrl_icache_if_tag_wen),
    .ifu_hpcp_icache_miss_pre(ifu_hpcp_icache_miss_pre),
    .ipb_icache_if_index(ipb_icache_if_index),
    .ipb_icache_if_req(ipb_icache_if_req),
    .ipb_icache_if_req_for_gateclk(ipb_icache_if_req_for_gateclk),
    .l1_refill_icache_if_fifo(l1_refill_icache_if_fifo),
    .l1_refill_icache_if_first(l1_refill_icache_if_first),
    .l1_refill_icache_if_index(l1_refill_icache_if_index),
    .l1_refill_icache_if_inst_data(l1_refill_icache_if_inst_data),
    .l1_refill_icache_if_last(l1_refill_icache_if_last),
    .l1_refill_icache_if_pre_code(l1_refill_icache_if_pre_code),
    .l1_refill_icache_if_ptag(l1_refill_icache_if_ptag),
    .l1_refill_icache_if_wr(l1_refill_icache_if_wr),
    .pad_yy_icg_scan_en(pad_yy_icg_scan_en),
    .pcgen_icache_if_chgflw(pcgen_icache_if_chgflw),
    .pcgen_icache_if_chgflw_bank0(pcgen_icache_if_chgflw_bank0),
    .pcgen_icache_if_chgflw_bank1(pcgen_icache_if_chgflw_bank1),
    .pcgen_icache_if_chgflw_bank2(pcgen_icache_if_chgflw_bank2),
    .pcgen_icache_if_chgflw_bank3(pcgen_icache_if_chgflw_bank3),
    .pcgen_icache_if_chgflw_short(pcgen_icache_if_chgflw_short),
    .pcgen_icache_if_gateclk_en(pcgen_icache_if_gateclk_en),
    .pcgen_icache_if_index(pcgen_icache_if_index),
    .pcgen_icache_if_seq_data_req(pcgen_icache_if_seq_data_req),
    .pcgen_icache_if_seq_data_req_short(pcgen_icache_if_seq_data_req_short),
    .pcgen_icache_if_seq_tag_req(pcgen_icache_if_seq_tag_req),
    .pcgen_icache_if_way_pred(pcgen_icache_if_way_pred),
    .icache_if_ifctrl_inst_data0(icache_if_ifctrl_inst_data0),
    .icache_if_ifctrl_inst_data1(icache_if_ifctrl_inst_data1),
    .icache_if_ifctrl_tag_data0(icache_if_ifctrl_tag_data0),
    .icache_if_ifctrl_tag_data1(icache_if_ifctrl_tag_data1),
    .icache_if_ifdp_fifo(icache_if_ifdp_fifo),
    .icache_if_ifdp_inst_data0(icache_if_ifdp_inst_data0),
    .icache_if_ifdp_inst_data1(icache_if_ifdp_inst_data1),
    .icache_if_ifdp_precode0(icache_if_ifdp_precode0),
    .icache_if_ifdp_precode1(icache_if_ifdp_precode1),
    .icache_if_ifdp_tag_data0(icache_if_ifdp_tag_data0),
    .icache_if_ifdp_tag_data1(icache_if_ifdp_tag_data1),
    .icache_if_ipb_tag_data0(icache_if_ipb_tag_data0),
    .icache_if_ipb_tag_data1(icache_if_ipb_tag_data1),
    .ifu_hpcp_icache_access(ifu_hpcp_icache_access),
    .ifu_hpcp_icache_miss(ifu_hpcp_icache_miss)
  );
endmodule
