module tb_case_003(
  input            bht_ifctrl_inv_done,
  input            bht_ifctrl_inv_on,
  input            btb_ifctrl_inv_done,
  input            btb_ifctrl_inv_on,
  input            cp0_ifu_bht_inv,
  input            cp0_ifu_btb_inv,
  input            cp0_ifu_icache_inv,
  input   [16:0]   cp0_ifu_icache_read_index,
  input            cp0_ifu_icache_read_req,
  input            cp0_ifu_icache_read_tag,
  input            cp0_ifu_icache_read_way,
  input            cp0_ifu_icg_en,
  input            cp0_ifu_ind_btb_inv,
  input            cp0_ifu_no_op_req,
  input            cp0_yy_clk_en,
  input            cpurst_b,
  input            forever_cpuclk,
  input            hpcp_ifu_cnt_en,
  input   [127:0]  icache_if_ifctrl_inst_data0,
  input   [127:0]  icache_if_ifctrl_inst_data1,
  input   [28:0]   icache_if_ifctrl_tag_data0,
  input   [28:0]   icache_if_ifctrl_tag_data1,
  output           ifctrl_bht_inv,
  output           ifctrl_bht_pipedown,
  output           ifctrl_bht_stall,
  output           ifctrl_btb_inv,
  output           ifctrl_debug_if_pc_vld,
  output           ifctrl_debug_if_stall,
  output           ifctrl_debug_if_vld,
  output  [3:0]    ifctrl_debug_inv_st,
  output           ifctrl_debug_lsu_all_inv,
  output           ifctrl_debug_lsu_line_inv,
  output           ifctrl_debug_mmu_pavld,
  output           ifctrl_debug_way_pred_stall,
  output  [38:0]   ifctrl_icache_if_index,
  output           ifctrl_icache_if_inv_fifo,
  output           ifctrl_icache_if_inv_on,
  output           ifctrl_icache_if_read_req_data0,
  output           ifctrl_icache_if_read_req_data1,
  output  [38:0]   ifctrl_icache_if_read_req_index,
  output           ifctrl_icache_if_read_req_tag,
  output           ifctrl_icache_if_reset_req,
  output           ifctrl_icache_if_tag_req,
  output  [2:0]    ifctrl_icache_if_tag_wen,
  output           ifctrl_ifdp_cancel,
  output           ifctrl_ifdp_pipedown,
  output           ifctrl_ifdp_stall,
  output           ifctrl_ind_btb_inv,
  output           ifctrl_ipb_inv_on,
  output           ifctrl_ipctrl_if_pcload,
  output           ifctrl_ipctrl_vld,
  output           ifctrl_l0_btb_inv,
  output           ifctrl_l0_btb_stall,
  output           ifctrl_l1_refill_ins_inv,
  output           ifctrl_l1_refill_ins_inv_dn,
  output           ifctrl_l1_refill_inv_busy,
  output           ifctrl_l1_refill_inv_on,
  output           ifctrl_lbuf_ins_inv_on,
  output           ifctrl_lbuf_inv_req,
  output           ifctrl_pcgen_chgflw_no_stall_mask,
  output           ifctrl_pcgen_chgflw_vld,
  output           ifctrl_pcgen_ins_icache_inv_done,
  output  [38:0]   ifctrl_pcgen_pcload_pc,
  output           ifctrl_pcgen_reissue_pcload,
  output           ifctrl_pcgen_stall,
  output           ifctrl_pcgen_stall_short,
  output  [1:0]    ifctrl_pcgen_way_pred,
  output           ifu_cp0_bht_inv_done,
  output           ifu_cp0_btb_inv_done,
  output           ifu_cp0_icache_inv_done,
  output  [127:0]  ifu_cp0_icache_read_data,
  output           ifu_cp0_icache_read_data_vld,
  output           ifu_cp0_ind_btb_inv_done,
  output           ifu_had_no_op,
  output           ifu_hpcp_frontend_stall,
  output           ifu_lsu_icache_inv_done,
  output           ifu_no_op_req,
  output           ifu_yy_xx_no_op,
  input            ind_btb_ifctrl_inv_done,
  input            ind_btb_ifctrl_inv_on,
  input            ipb_ifctrl_prefetch_idle,
  input            ipctrl_ifctrl_bht_stall,
  input            ipctrl_ifctrl_stall,
  input            ipctrl_ifctrl_stall_short,
  input   [38:0]   l0_btb_ifctrl_chgflw_pc,
  input   [1:0]    l0_btb_ifctrl_chgflw_way_pred,
  input            l0_btb_ifctrl_chglfw_vld,
  input            l1_refill_ifctrl_ctc,
  input            l1_refill_ifctrl_idle,
  input   [38:0]   l1_refill_ifctrl_pc,
  input            l1_refill_ifctrl_refill_on,
  input            l1_refill_ifctrl_reissue,
  input            l1_refill_ifctrl_start,
  input            l1_refill_ifctrl_start_for_gateclk,
  input            l1_refill_ifctrl_trans_cmplt,
  input            l1_refill_inv_wfd_back,
  input            lsu_ifu_icache_all_inv,
  input   [5:0]    lsu_ifu_icache_index,
  input            lsu_ifu_icache_line_inv,
  input   [27:0]   lsu_ifu_icache_ptag,
  input            mmu_ifu_pavld,
  input            pad_yy_icg_scan_en,
  input            pcgen_ifctrl_cancel,
  input   [38:0]   pcgen_ifctrl_pc,
  input            pcgen_ifctrl_pipe_cancel,
  input            pcgen_ifctrl_reissue,
  input   [1:0]    pcgen_ifctrl_way_pred,
  input            pcgen_ifctrl_way_pred_stall,
  input            rtu_ifu_xx_dbgon,
  input            vector_ifctrl_reset_on,
  input            vector_ifctrl_sm_on,
  input            vector_ifctrl_sm_start
);

  ct_ifu_ifctrl dut (
    .bht_ifctrl_inv_done(bht_ifctrl_inv_done),
    .bht_ifctrl_inv_on(bht_ifctrl_inv_on),
    .btb_ifctrl_inv_done(btb_ifctrl_inv_done),
    .btb_ifctrl_inv_on(btb_ifctrl_inv_on),
    .cp0_ifu_bht_inv(cp0_ifu_bht_inv),
    .cp0_ifu_btb_inv(cp0_ifu_btb_inv),
    .cp0_ifu_icache_inv(cp0_ifu_icache_inv),
    .cp0_ifu_icache_read_index(cp0_ifu_icache_read_index),
    .cp0_ifu_icache_read_req(cp0_ifu_icache_read_req),
    .cp0_ifu_icache_read_tag(cp0_ifu_icache_read_tag),
    .cp0_ifu_icache_read_way(cp0_ifu_icache_read_way),
    .cp0_ifu_icg_en(cp0_ifu_icg_en),
    .cp0_ifu_ind_btb_inv(cp0_ifu_ind_btb_inv),
    .cp0_ifu_no_op_req(cp0_ifu_no_op_req),
    .cp0_yy_clk_en(cp0_yy_clk_en),
    .cpurst_b(cpurst_b),
    .forever_cpuclk(forever_cpuclk),
    .hpcp_ifu_cnt_en(hpcp_ifu_cnt_en),
    .icache_if_ifctrl_inst_data0(icache_if_ifctrl_inst_data0),
    .icache_if_ifctrl_inst_data1(icache_if_ifctrl_inst_data1),
    .icache_if_ifctrl_tag_data0(icache_if_ifctrl_tag_data0),
    .icache_if_ifctrl_tag_data1(icache_if_ifctrl_tag_data1),
    .ifctrl_bht_inv(ifctrl_bht_inv),
    .ifctrl_bht_pipedown(ifctrl_bht_pipedown),
    .ifctrl_bht_stall(ifctrl_bht_stall),
    .ifctrl_btb_inv(ifctrl_btb_inv),
    .ifctrl_debug_if_pc_vld(ifctrl_debug_if_pc_vld),
    .ifctrl_debug_if_stall(ifctrl_debug_if_stall),
    .ifctrl_debug_if_vld(ifctrl_debug_if_vld),
    .ifctrl_debug_inv_st(ifctrl_debug_inv_st),
    .ifctrl_debug_lsu_all_inv(ifctrl_debug_lsu_all_inv),
    .ifctrl_debug_lsu_line_inv(ifctrl_debug_lsu_line_inv),
    .ifctrl_debug_mmu_pavld(ifctrl_debug_mmu_pavld),
    .ifctrl_debug_way_pred_stall(ifctrl_debug_way_pred_stall),
    .ifctrl_icache_if_index(ifctrl_icache_if_index),
    .ifctrl_icache_if_inv_fifo(ifctrl_icache_if_inv_fifo),
    .ifctrl_icache_if_inv_on(ifctrl_icache_if_inv_on),
    .ifctrl_icache_if_read_req_data0(ifctrl_icache_if_read_req_data0),
    .ifctrl_icache_if_read_req_data1(ifctrl_icache_if_read_req_data1),
    .ifctrl_icache_if_read_req_index(ifctrl_icache_if_read_req_index),
    .ifctrl_icache_if_read_req_tag(ifctrl_icache_if_read_req_tag),
    .ifctrl_icache_if_reset_req(ifctrl_icache_if_reset_req),
    .ifctrl_icache_if_tag_req(ifctrl_icache_if_tag_req),
    .ifctrl_icache_if_tag_wen(ifctrl_icache_if_tag_wen),
    .ifctrl_ifdp_cancel(ifctrl_ifdp_cancel),
    .ifctrl_ifdp_pipedown(ifctrl_ifdp_pipedown),
    .ifctrl_ifdp_stall(ifctrl_ifdp_stall),
    .ifctrl_ind_btb_inv(ifctrl_ind_btb_inv),
    .ifctrl_ipb_inv_on(ifctrl_ipb_inv_on),
    .ifctrl_ipctrl_if_pcload(ifctrl_ipctrl_if_pcload),
    .ifctrl_ipctrl_vld(ifctrl_ipctrl_vld),
    .ifctrl_l0_btb_inv(ifctrl_l0_btb_inv),
    .ifctrl_l0_btb_stall(ifctrl_l0_btb_stall),
    .ifctrl_l1_refill_ins_inv(ifctrl_l1_refill_ins_inv),
    .ifctrl_l1_refill_ins_inv_dn(ifctrl_l1_refill_ins_inv_dn),
    .ifctrl_l1_refill_inv_busy(ifctrl_l1_refill_inv_busy),
    .ifctrl_l1_refill_inv_on(ifctrl_l1_refill_inv_on),
    .ifctrl_lbuf_ins_inv_on(ifctrl_lbuf_ins_inv_on),
    .ifctrl_lbuf_inv_req(ifctrl_lbuf_inv_req),
    .ifctrl_pcgen_chgflw_no_stall_mask(ifctrl_pcgen_chgflw_no_stall_mask),
    .ifctrl_pcgen_chgflw_vld(ifctrl_pcgen_chgflw_vld),
    .ifctrl_pcgen_ins_icache_inv_done(ifctrl_pcgen_ins_icache_inv_done),
    .ifctrl_pcgen_pcload_pc(ifctrl_pcgen_pcload_pc),
    .ifctrl_pcgen_reissue_pcload(ifctrl_pcgen_reissue_pcload),
    .ifctrl_pcgen_stall(ifctrl_pcgen_stall),
    .ifctrl_pcgen_stall_short(ifctrl_pcgen_stall_short),
    .ifctrl_pcgen_way_pred(ifctrl_pcgen_way_pred),
    .ifu_cp0_bht_inv_done(ifu_cp0_bht_inv_done),
    .ifu_cp0_btb_inv_done(ifu_cp0_btb_inv_done),
    .ifu_cp0_icache_inv_done(ifu_cp0_icache_inv_done),
    .ifu_cp0_icache_read_data(ifu_cp0_icache_read_data),
    .ifu_cp0_icache_read_data_vld(ifu_cp0_icache_read_data_vld),
    .ifu_cp0_ind_btb_inv_done(ifu_cp0_ind_btb_inv_done),
    .ifu_had_no_op(ifu_had_no_op),
    .ifu_hpcp_frontend_stall(ifu_hpcp_frontend_stall),
    .ifu_lsu_icache_inv_done(ifu_lsu_icache_inv_done),
    .ifu_no_op_req(ifu_no_op_req),
    .ifu_yy_xx_no_op(ifu_yy_xx_no_op),
    .ind_btb_ifctrl_inv_done(ind_btb_ifctrl_inv_done),
    .ind_btb_ifctrl_inv_on(ind_btb_ifctrl_inv_on),
    .ipb_ifctrl_prefetch_idle(ipb_ifctrl_prefetch_idle),
    .ipctrl_ifctrl_bht_stall(ipctrl_ifctrl_bht_stall),
    .ipctrl_ifctrl_stall(ipctrl_ifctrl_stall),
    .ipctrl_ifctrl_stall_short(ipctrl_ifctrl_stall_short),
    .l0_btb_ifctrl_chgflw_pc(l0_btb_ifctrl_chgflw_pc),
    .l0_btb_ifctrl_chgflw_way_pred(l0_btb_ifctrl_chgflw_way_pred),
    .l0_btb_ifctrl_chglfw_vld(l0_btb_ifctrl_chglfw_vld),
    .l1_refill_ifctrl_ctc(l1_refill_ifctrl_ctc),
    .l1_refill_ifctrl_idle(l1_refill_ifctrl_idle),
    .l1_refill_ifctrl_pc(l1_refill_ifctrl_pc),
    .l1_refill_ifctrl_refill_on(l1_refill_ifctrl_refill_on),
    .l1_refill_ifctrl_reissue(l1_refill_ifctrl_reissue),
    .l1_refill_ifctrl_start(l1_refill_ifctrl_start),
    .l1_refill_ifctrl_start_for_gateclk(l1_refill_ifctrl_start_for_gateclk),
    .l1_refill_ifctrl_trans_cmplt(l1_refill_ifctrl_trans_cmplt),
    .l1_refill_inv_wfd_back(l1_refill_inv_wfd_back),
    .lsu_ifu_icache_all_inv(lsu_ifu_icache_all_inv),
    .lsu_ifu_icache_index(lsu_ifu_icache_index),
    .lsu_ifu_icache_line_inv(lsu_ifu_icache_line_inv),
    .lsu_ifu_icache_ptag(lsu_ifu_icache_ptag),
    .mmu_ifu_pavld(mmu_ifu_pavld),
    .pad_yy_icg_scan_en(pad_yy_icg_scan_en),
    .pcgen_ifctrl_cancel(pcgen_ifctrl_cancel),
    .pcgen_ifctrl_pc(pcgen_ifctrl_pc),
    .pcgen_ifctrl_pipe_cancel(pcgen_ifctrl_pipe_cancel),
    .pcgen_ifctrl_reissue(pcgen_ifctrl_reissue),
    .pcgen_ifctrl_way_pred(pcgen_ifctrl_way_pred),
    .pcgen_ifctrl_way_pred_stall(pcgen_ifctrl_way_pred_stall),
    .rtu_ifu_xx_dbgon(rtu_ifu_xx_dbgon),
    .vector_ifctrl_reset_on(vector_ifctrl_reset_on),
    .vector_ifctrl_sm_on(vector_ifctrl_sm_on),
    .vector_ifctrl_sm_start(vector_ifctrl_sm_start)
  );
endmodule
