module tb_case_002(
  input         l2c_data_clk_x,
  input [511:0] l2c_data_din,
  output [511:0] l2c_data_dout,
  input [12:0]  l2c_data_index0,
  input [12:0]  l2c_data_index1,
  input [12:0]  l2c_data_index2,
  input [12:0]  l2c_data_index3,
  input [3:0]   l2c_data_ram_cen,
  input [3:0]   l2c_data_wen,
  input [143:0] l2c_dirty_din,
  output [143:0] l2c_dirty_dout,
  input         l2c_dirty_gwen,
  input         l2c_dirty_ram_cen,
  input [143:0] l2c_dirty_wen,
  input         l2c_tag_clk_x,
  input [383:0] l2c_tag_din,
  output [383:0] l2c_tag_dout,
  input         l2c_tag_gwen,
  input [8:0]   l2c_tag_index,
  input         l2c_tag_ram_cen,
  input [383:0] l2c_tag_wen,
  input         pad_yy_icg_scan_en
);

  ct_l2cache_top dut (
    .l2c_data_clk_x(l2c_data_clk_x),
    .l2c_data_din(l2c_data_din),
    .l2c_data_dout(l2c_data_dout),
    .l2c_data_index0(l2c_data_index0),
    .l2c_data_index1(l2c_data_index1),
    .l2c_data_index2(l2c_data_index2),
    .l2c_data_index3(l2c_data_index3),
    .l2c_data_ram_cen(l2c_data_ram_cen),
    .l2c_data_wen(l2c_data_wen),
    .l2c_dirty_din(l2c_dirty_din),
    .l2c_dirty_dout(l2c_dirty_dout),
    .l2c_dirty_gwen(l2c_dirty_gwen),
    .l2c_dirty_ram_cen(l2c_dirty_ram_cen),
    .l2c_dirty_wen(l2c_dirty_wen),
    .l2c_tag_clk_x(l2c_tag_clk_x),
    .l2c_tag_din(l2c_tag_din),
    .l2c_tag_dout(l2c_tag_dout),
    .l2c_tag_gwen(l2c_tag_gwen),
    .l2c_tag_index(l2c_tag_index),
    .l2c_tag_ram_cen(l2c_tag_ram_cen),
    .l2c_tag_wen(l2c_tag_wen),
    .pad_yy_icg_scan_en(pad_yy_icg_scan_en)
  );
endmodule
